POST http://localhost:8090/bands
Content-Type: application/json

{
    "name": "The Beatles", 
    "genre": "Rock", 
    "albums":[
        {
            "title": "Abbey Road", 
            "release_date": "1969-09-26"
        },
        {
            "title": "Sgt. Pepper's Lonely Hearts Club Band", 
            "release_date": "1967-05-26"
        }
    ]
}


###
GET http://localhost:8090/about/

###
GET http://localhost:8090/bands/

###
GET http://localhost:8090/bands/2

###
GET http://localhost:8090/bands/genre/Metal

###
GET http://localhost:8090/bands/genre/Rock


###
POST http://localhost:8090/bands
Content-Type: application/json

{
    "name": "Boards of Canada",
    "genre": "Electronic"
}
