POST http://localhost:8000/bands
Content-Type: application/json

{
    "name": "New Band",
    "genre": "rock",
    "albums": [
        {
            "title": "Debut Album",
            "release_date": "2023-01-01"
        }
    ]
}

###
GET http://localhost:8000/bands/

###
GET http://localhost:8000/bands/1

###
GET http://localhost:8000/bands/genre/metal

###
POST http://localhost:8000/bands
Content-Type: application/json

{
    "name": "New Band",
    "genre": "METAL"
}
